Smile 1126 active and inactive authors presentation
BIBSYSDEV/sentralimport-react-frontend pull request #14
Opened 2021-11-29 11:41 UTC by anetteOlli

2021-11-29 14:31 UTC, pcb-unit requested changes

2021-11-29 14:31 UTC, pcb-unit commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +      <hr />
bytte ut med material Divider ?

2021-11-29 14:31 UTC, pcb-unit commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +      {contributor.affiliations?.map((affiliation: any, h: number) => (
Kan sikkert snike inn typer her også mens du holder på ;-)

2021-11-29 14:31 UTC, pcb-unit commented on cypress/integration/contributor.spec.js
> +    cy.get('[data-testid="author-name-1234567"]')
author-name-${mockPerson.cristin_person_id} ?

2021-11-30 09:05 UTC, anetteOlli commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +      <hr />
Tenkte å ta alt med layouten her i neste task

2021-11-30 09:33 UTC, pcb-unit commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +  & path {
måtte bare sjekke... om man vil kjøre et filter kan man bruke :   filter: invert(62%) sepia(0%) saturate(0%) hue-rotate(284deg) brightness(97%) contrast(91%); :-)
Alternativt kan man også endre direkte i svg'en

2021-11-30 09:34 UTC, pcb-unit commented on src/assets/styles/StyleConstants.ts
> +    OPAQUE_30_BLACK: 'rgba(0, 0, 0, 0.41)',
30 ?

2021-11-30 09:53 UTC, anetteOlli commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +  & path {
Ja, så det også gikk an i inkscape direkte i svg'en, men jeg liker ideen om at vi kan endre fargen etter behov. F.eks nå kan iconene bli brukt på knapper og da har vi allerede brukermanualen til hvordan vi får endret fargene.

2021-11-30 09:56 UTC, anetteOlli commented on src/assets/styles/StyleConstants.ts
> +    OPAQUE_30_BLACK: 'rgba(0, 0, 0, 0.41)',
Fikset.

2021-11-30 09:56 UTC, anetteOlli commented on cypress/integration/contributor.spec.js
> +    cy.get('[data-testid="author-name-1234567"]')
Fikset

2021-11-30 09:56 UTC, anetteOlli commented on src/Components/Contributors/ContributorSearchResultItem.tsx
> +      {contributor.affiliations?.map((affiliation: any, h: number) => (
Fikset

2021-11-30 10:18 UTC, pcb-unit approved these changes

2021-11-30 10:23 UTC, merged