Smile 1454 show/hide contributors in monster post
BIBSYSDEV/sentralimport-react-frontend pull request #208
Opened 2022-03-24 12:09 UTC by pcb-unit

2022-03-24 12:10 UTC, pcb-unit commented on src/Components/ComparePublicationData/ComparePublicationDataModal.tsx
> +      {importPublication && contributors && isContributorModalOpen && (
Må nesten ha den sånn for å hindre utallige renders av modalen

2022-03-24 12:11 UTC, pcb-unit commented on src/Components/Contributors/ContributorModal.tsx
> +  contributor.toBeCreated?.surname?.length > MaxLengthLastName;
Fant ut det var bedre å ha denne logikken flere steder enn å lage noe alt for komplekst system som holder det globalt

2022-03-29 08:01 UTC, anetteOlli requested changes

2022-03-29 09:25 UTC, pcb-unit commented on src/Components/Contributors/ContributorModal.tsx
> +                        hideArrows={listOfHiddenContributors[index]}
fikset

2022-03-29 09:25 UTC, pcb-unit commented on src/Components/Contributors/ContributorModal.tsx
> +                            {contributor.imported.first_name + ' ' + contributor.imported.surname}{' '}
fikset

2022-03-29 09:31 UTC, pcb-unit commented on src/Components/Contributors/ContributorModal.tsx
> +  );
bra observert. men jeg tenkte det slikt at denne brukes kun for å skjule uinterresante poster ved visning av en monsterpost . Om en contributor endres trenger ikke denne logikken oppdateres, men de som er åpnet/lukket

2022-03-29 11:10 UTC, anetteOlli commented on src/Components/Contributors/ContributorModal.tsx
> +  );
Nå oppdateres den vel på hver rendring? Så hvis den kun skal settes én gang så kanskje i en useEffect med tom dependency array?

2022-03-29 12:47 UTC, pcb-unit commented on src/Components/Contributors/ContributorModal.tsx
> +  );
fikset - den trengte ikke ligge i init i det hele tatt - da den kun brukes ved en click-handler

2022-03-31 11:26 UTC, anetteOlli approved these changes

2022-03-31 11:29 UTC, merged