SMILE-1469-another_lookup
BIBSYSDEV/sentralimport-react-frontend pull request #209
Opened 2022-03-24 14:41 UTC by pcb-unit

2022-03-24 14:42 UTC, pcb-unit commented on src/api/institutionApi.ts
> +export async function getInstitutionNameNoCache(
Jeg gav opp å finne ut hvordan den gamle koden hang sammen  og lagde en ny api-metode isteded. 

Kanskje vi kunne ha brukt et cache-adapter på axios for å forenkle cache-problematikken ?

2022-03-29 08:10 UTC, anetteOlli requested changes

2022-03-29 08:10 UTC, anetteOlli commented on src/Components/Contributors/InstututionHelper.ts
> +  } else if (affiliation.cristinInstitutionNr?.toString() !== '0') {
Kan ikke dette kallet feile fordi institusjonen ikke eksisterer lengre?
Wrappes inni en try catch?

2022-03-29 09:16 UTC, pcb-unit commented on src/Components/Contributors/InstututionHelper.ts
> +  } else if (affiliation.cristinInstitutionNr?.toString() !== '0') {
try catchen ligger i api-funksjonen - slik at man uansett får en string tilbake. ref: "NAVN IKKE FUNNET..."

2022-03-29 11:11 UTC, anetteOlli approved these changes

2022-03-29 11:14 UTC, merged