SMILE-1181-bug-calculating-page-count-for-journals
BIBSYSDEV/sentralimport-react-frontend pull request #36
Opened 2021-12-06 13:02 UTC by anetteOlli

2021-12-06 14:29 UTC, pcb-unit requested changes

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +  } else if (pageTo - pageFrom > Math.pow(2, 31)) {
trenger vel egentlig ikke denne med den regexpen ?

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +    !isNaN(pageFrom) ||
trenger kanskje ikke denne heller med regexpen.

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +  const reg = new RegExp('^[0-9]+$');
kan legge inn en kommentar på  hvorfor vi gjør det slik - det glemmer man fort

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +    !reg.test(pageFrom.toString())
hva med versjonen : `numberMatcher=/^[0-9]+$/i;  pageFrom.match(numberMatcher)  `

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +      <pre style={{ maxWidth: '90%' }}>{JSON.stringify(createPublicationObject(), null, 2)}</pre>
du glemte denne :-)

2021-12-06 14:29 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +        count: getNumberOfPages(publication.channel.pageFrom, publication.channel.pageTo),
nice

2021-12-06 14:30 UTC, anetteOlli commented on src/Components/Dialogs/ConfirmImportDialog.js
> +  } else if (pageTo - pageFrom > Math.pow(2, 31)) {
PageTo: 345345352345345345345345341232323 PageFrom 0. vil gå igjennom regex'en og isNAN, men krasje backenden.

2021-12-06 14:56 UTC, anetteOlli commented on src/Components/Dialogs/ConfirmImportDialog.js
> +      <pre style={{ maxWidth: '90%' }}>{JSON.stringify(createPublicationObject(), null, 2)}</pre>
takk, takk

2021-12-06 14:57 UTC, anetteOlli commented on src/Components/Dialogs/ConfirmImportDialog.js
> +    !reg.test(pageFrom.toString())
fikset

2021-12-06 14:57 UTC, anetteOlli commented on src/Components/Dialogs/ConfirmImportDialog.js
> +    !isNaN(pageFrom) ||
fikset

2021-12-06 15:16 UTC, pcb-unit submitted a review, later dismissed

2021-12-07 07:19 UTC, pcb-unit commented on src/Components/Dialogs/ConfirmImportDialog.js
> +  const reg = /^[0-9]+$/i;
hva med arabicNumberMatcher ?

2021-12-07 09:28 UTC, merged